name = "proxify-cf"
main = "src/index.ts"
compatibility_date = "2026-04-30"
compatibility_flags = ["nodejs_compat"]

preview_urls = true
workers_dev = true

# Custom Domain (Worker is the origin)
[[routes]]
pattern = "proxify.rjoshi.net"
custom_domain = true

# Route (Worker runs in front of an existing origin)
[[routes]]
pattern = "santosh-gemma.rjoshi.net"
zone_name = "rjoshi.net"

[[d1_databases]]
binding = "DB"
database_name = "proxify-db"
database_id = "25526790-127c-4f8a-9b0d-367db37d3206"
migrations_dir = "./migrations"

[[kv_namespaces]]
binding = "proxify_cache"
id = "5044cff968f64f248d498b0264112beb"

[vars]
CF_ACCESS_TEAM_DOMAIN = ""
CF_ACCESS_AUD = ""
LOCAL_ADMIN_EMAIL = "mail@rjoshi.net"
# KEK should be added as a secret in production

[assets]
directory = "../admin/dist"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "single-page-application"
